CREATE TYPE "ArtStyle" AS ENUM (
    'PREMIUM_LUXO',
    'CLEAN_MODERNO',
    'CORPORATIVO',
    'MINIMALISTA',
    'IMPACTO_COMERCIAL',
    'PROMOCIONAL',
    'INSTITUCIONAL',
    'EDUCATIVO',
    'MEDICO_PREMIUM',
    'AUTOMOTIVO_PERFORMANCE',
    'LOGISTICA_FORTE',
    'ELEGANCIA_FEMININA',
    'ALTO_PADRAO'
);

ALTER TABLE "generated_arts" ADD COLUMN "style" "ArtStyle";
